server:
  port: 8930

timebase:
  url: dxtick://localhost:8011

connectors:
  coinbase:
    stream: coinbase
    wsUrl: wss://ws-feed.pro.coinbase.com
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "ETH-USD,BTC-USD,BTC-USDT,LTC-USD"

  kraken-spot:
    stream: kraken-spot
    wsUrl: wss://ws.kraken.com
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "XBT/USD,XBT/USDT,ETH/USD,ETH/USDT,USDT/USD"

  kraken-futures:
    stream: kraken-futures
    wsUrl: wss://futures.kraken.com/ws/v1
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "PF_XBTUSD,PI_XRPUSD,PF_ETHUSD,FI_XBTUSD_220930"

  bitmex:
    stream: bitmex
    wsUrl: wss://ws.bitmex.com/realtime
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "XBTUSD=BTC/USD,ETHUSD=ETH/USD"

  huobi-spot:
    stream: huobi-spot
    wsUrl: wss://api.huobi.pro/ws
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "btcusdt,ethbtc"

  huobi-futures:
    stream: huobi-futures
    wsUrl: wss://api.hbdm.com/ws
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "BTC220930, LTC220930"

  ftx:
    stream: ftx
    wsUrl: wss://ftx.com/ws
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "USDT-PERP,LTC/USDT"

  bybit-linear-futures:
    type: bybit-futures
    stream: bybit-futures
    wsUrl: wss://stream.bybit.com/realtime_public # linear futures
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "LTCUSDT=LTC/USDT,ADAUSDT=ADA/USDT"

  bybit-inverse-futures:
    type: bybit-futures
    stream: bybit-futures
    wsUrl: wss://stream.bybit.com/realtime # inverse futures
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "MANAUSD=MANA/USD,LUNAUSD=LUNA/USD"

  bybit-spot:
    stream: bybit-spot
    wsUrl: wss://stream.bybit.com/spot/quote/ws/v1
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "BTCUSDT=BTC/USDT,ETHUSDT=ETH/USDT"

  okex:
    stream: okex
    wsUrl: wss://ws.okex.com:8443/ws/v5/public
    depth: 20
    model:
      - "L1"
      - "L2"
      - "TRADES"
    instruments: "BTC-UST,BTC-USDT-220930"
