version: "3"
services:
  timebase:
    image: "finos/timebase-ce-server:6.1"    
    stop_grace_period: 5m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - JAVA_OPTS=
        -Xms8g
        -Xmx8g        
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/timebase-home/timebase.hprof
        -Xlog:gc=debug:file=/timebase-home/GClog-TimeBase.log:time,uptime,level,tags:filecount=5,filesize=100m
    ports:
      - 8011:8011
    volumes:
      - "./timebase-home:/timebase-home"

  timebase-admin:
    image: "epam/timebase-ws-server:latest"
    environment:
      - JAVA_OPTS=
        -Xmx1g
        -Dserver.port=8099
        -Dtimebase.url=dxtick://timebase:8011
        -Dserver.compression.enabled=true
        -Dserver.compression.mime-types=text/html,text/css,application/javascript,application/json
    ports:
      - 8099:8099
    depends_on:
      - timebase

  crypto-connectors:
    image: "epam/timebase-crypto-connectors:0.1.4"
    environment:
      - JAVA_OPTS=
        -Xmx1g
        -Dserver.port=8055
        -Dtimebase.url=dxtick://timebase:8011
        -Dserver.compression.enabled=true
        -Dserver.compression.mime-types=text/html,text/css,application/javascript,application/json
    ports:
      - 8055:8055
    depends_on:
      - timebase      